
import React, { useState, useEffect } from 'react';
import { 
  FiFileText, FiDownload, FiCopy, FiRefreshCw, FiCheck, FiCpu, 
  FiCalendar, FiList, FiEdit3, FiTrash2, FiSearch, FiArrowRight,
  FiMoreHorizontal, FiTag, FiBox
} from 'react-icons/fi';
import { TbSparkles, TbMarkdown, TbHistory, TbClipboardCheck, TbFileTypePdf, TbRocket } from 'react-icons/tb';
import { Modal } from './Modal';

// --- TYPES ---

interface ChangelogEntry {
  id: string;
  title: string;
  version: string;
  date: string;
  content: string; // Markdown
  status: 'Draft' | 'Published';
  source: string; // e.g. "Sprint 4" or "v2.1.0"
}

interface MockTask {
  id: string;
  title: string;
  type: 'Feature' | 'Bug' | 'Chore';
  status: 'Done' | 'In Progress';
}

// --- MOCK DATA ---

const MOCK_SOURCES = [
  { id: 's4', label: 'Sprint 4', type: 'Sprint', date: 'Oct 24 - Nov 07' },
  { id: 's3', label: 'Sprint 3', type: 'Sprint', date: 'Oct 10 - Oct 23' },
  { id: 'v2.1', label: 'Release v2.1.0', type: 'Release', date: 'Oct 25' },
];

const MOCK_TASKS: Record<string, MockTask[]> = {
  's4': [
    { id: 'FLX-101', title: 'Implement OAuth2 Login Flow', type: 'Feature', status: 'Done' },
    { id: 'FLX-104', title: 'Fix Session Timeout on Mobile', type: 'Bug', status: 'Done' },
    { id: 'FLX-112', title: 'Update API Documentation', type: 'Chore', status: 'Done' },
    { id: 'FLX-115', title: 'Refactor Sidebar Navigation', type: 'Feature', status: 'Done' },
  ],
  'v2.1': [
    { id: 'FLX-201', title: 'Dashboard Analytics Widgets', type: 'Feature', status: 'Done' },
    { id: 'FLX-205', title: 'Patch Security Vulnerability in Deps', type: 'Bug', status: 'Done' },
  ]
};

const INITIAL_HISTORY: ChangelogEntry[] = [
  {
    id: 'cl-1',
    title: 'v2.0.4 Hotfix',
    version: 'v2.0.4',
    date: '2023-10-20',
    content: `# v2.0.4 Hotfix\n\n## 🐛 Bug Fixes\n- Fixed login timeout issue reported by enterprise users.\n- Resolved Z-index conflict on modal overlays.\n`,
    status: 'Published',
    source: 'Release v2.0.4'
  }
];

// --- COMPONENT ---

export const ChangelogGenerator: React.FC = () => {
  // State
  const [history, setHistory] = useState<ChangelogEntry[]>(INITIAL_HISTORY);
  const [selectedSourceId, setSelectedSourceId] = useState<string>(MOCK_SOURCES[0].id);
  const [generatedContent, setGeneratedContent] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeEntry, setActiveEntry] = useState<ChangelogEntry | null>(null);
  const [viewMode, setViewMode] = useState<'editor' | 'preview'>('preview');
  const [toast, setToast] = useState<string | null>(null);

  // Handlers
  const showToast = (msg: string) => {
    setToast(msg);
    setTimeout(() => setToast(null), 3000);
  };

  const generateChangelog = () => {
    setIsGenerating(true);
    
    // Simulate AI Latency
    setTimeout(() => {
      const source = MOCK_SOURCES.find(s => s.id === selectedSourceId);
      const tasks = MOCK_TASKS[selectedSourceId] || [];
      
      const features = tasks.filter(t => t.type === 'Feature');
      const bugs = tasks.filter(t => t.type === 'Bug');
      const chores = tasks.filter(t => t.type === 'Chore');

      const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

      let markdown = `# Changelog - ${source?.label}\n_${today}_\n\n`;
      
      if (features.length > 0) {
        markdown += `## 🚀 New Features\n`;
        features.forEach(t => markdown += `- ${t.title} (${t.id})\n`);
        markdown += `\n`;
      }

      if (bugs.length > 0) {
        markdown += `## 🐛 Bug Fixes\n`;
        bugs.forEach(t => markdown += `- ${t.title} (${t.id})\n`);
        markdown += `\n`;
      }

      if (chores.length > 0) {
        markdown += `## 🛠 Improvements\n`;
        chores.forEach(t => markdown += `- ${t.title} (${t.id})\n`);
      }

      markdown += `\n---\n*Generated by Flownyx AI*`;

      const newEntry: ChangelogEntry = {
        id: `cl-${Date.now()}`,
        title: `Changelog for ${source?.label}`,
        version: 'Draft',
        date: new Date().toISOString().split('T')[0],
        content: markdown,
        status: 'Draft',
        source: source?.label || 'Unknown'
      };

      setHistory([newEntry, ...history]);
      setActiveEntry(newEntry);
      setGeneratedContent(markdown);
      setIsGenerating(false);
      showToast('Changelog generated successfully');
    }, 1500);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedContent);
    showToast('Copied to clipboard');
  };

  const handleSave = () => {
    if (activeEntry) {
      const updated = { ...activeEntry, content: generatedContent, status: 'Published' as const };
      setHistory(history.map(h => h.id === activeEntry.id ? updated : h));
      setActiveEntry(updated);
      showToast('Changelog published');
    }
  };

  const handleDelete = (id: string) => {
    if (window.confirm('Delete this changelog?')) {
      setHistory(history.filter(h => h.id !== id));
      if (activeEntry?.id === id) {
        setActiveEntry(null);
        setGeneratedContent('');
      }
    }
  };

  const selectHistoryItem = (entry: ChangelogEntry) => {
    setActiveEntry(entry);
    setGeneratedContent(entry.content);
  };

  return (
    <div className="h-full flex flex-col bg-pepper-50 dark:bg-pepper-950 overflow-hidden animate-fade-in relative">
      {toast && (
        <div className="fixed bottom-6 right-6 z-[200] px-4 py-3 bg-pepper-900 text-white rounded-xl shadow-lg flex items-center gap-3 animate-slide-up">
          <FiCheck />
          <span className="text-sm font-bold">{toast}</span>
        </div>
      )}

      {/* HEADER */}
      <div className="h-20 px-8 border-b border-pepper-200 dark:border-pepper-800 flex justify-between items-center bg-white dark:bg-pepper-900 shrink-0 z-20">
        <div>
          <h1 className="text-2xl font-display font-extrabold text-pepper-900 dark:text-white flex items-center gap-3">
            <TbSparkles className="text-pepper-400" /> AI Changelog Generator
          </h1>
          <p className="text-xs text-pepper-500 dark:text-pepper-400 mt-1 font-medium">Automated release notes and documentation</p>
        </div>
        <div className="flex items-center gap-3">
           <div className="hidden md:flex items-center gap-2 px-3 py-1.5 bg-pepper-50 dark:bg-pepper-800 rounded-lg border border-pepper-200 dark:border-pepper-700">
              <span className="text-xs text-pepper-500 font-bold uppercase tracking-wider">Model:</span>
              <span className="text-xs font-bold text-pepper-900 dark:text-white flex items-center gap-1"><FiCpu /> Gemini 2.5</span>
           </div>
        </div>
      </div>

      {/* CONTENT */}
      <div className="flex-1 flex overflow-hidden">
        
        {/* LEFT SIDEBAR (CONFIG & HISTORY) */}
        <div className="w-80 bg-white dark:bg-pepper-900 border-r border-pepper-200 dark:border-pepper-800 flex flex-col shrink-0 z-10">
           
           {/* Generator Config */}
           <div className="p-6 border-b border-pepper-100 dark:border-pepper-800">
              <h3 className="text-xs font-bold text-pepper-400 uppercase tracking-wider mb-4 flex items-center gap-2">
                 <FiRefreshCw /> Generator
              </h3>
              
              <div className="space-y-4">
                 <div>
                    <label className="block text-[10px] font-bold text-pepper-500 uppercase mb-1.5">Source</label>
                    <div className="relative">
                        <select 
                          value={selectedSourceId}
                          onChange={(e) => setSelectedSourceId(e.target.value)}
                          className="w-full bg-pepper-50 dark:bg-pepper-800 border border-pepper-200 dark:border-pepper-700 rounded-xl px-3 py-2.5 text-sm font-medium text-pepper-900 dark:text-white outline-none focus:ring-2 focus:ring-pepper-900/20 appearance-none"
                        >
                           {MOCK_SOURCES.map(s => (
                             <option key={s.id} value={s.id}>{s.label} ({s.type})</option>
                           ))}
                        </select>
                        <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-pepper-400">
                           <FiCalendar />
                        </div>
                    </div>
                 </div>

                 <button 
                    onClick={generateChangelog}
                    disabled={isGenerating}
                    className={`w-full py-3 bg-pepper-900 dark:bg-white text-white dark:text-pepper-900 rounded-xl text-sm font-bold shadow-md hover:shadow-lg transition-all flex items-center justify-center gap-2 ${isGenerating ? 'opacity-80 cursor-wait' : 'hover:-translate-y-0.5'}`}
                 >
                    {isGenerating ? <FiRefreshCw className="animate-spin" /> : <TbSparkles />}
                    {isGenerating ? 'Generating...' : 'Generate Changelog'}
                 </button>
              </div>
           </div>

           {/* History List */}
           <div className="flex-1 overflow-y-auto custom-scrollbar p-4">
              <h3 className="text-xs font-bold text-pepper-400 uppercase tracking-wider mb-3 px-2 flex items-center gap-2">
                 <TbHistory /> History
              </h3>
              <div className="space-y-2">
                 {history.map(entry => (
                    <div 
                      key={entry.id}
                      onClick={() => selectHistoryItem(entry)}
                      className={`group p-3 rounded-xl border transition-all cursor-pointer relative ${activeEntry?.id === entry.id ? 'bg-pepper-50 dark:bg-pepper-800 border-pepper-300 dark:border-pepper-600 shadow-sm' : 'bg-transparent border-transparent hover:bg-pepper-50 dark:hover:bg-pepper-800/50'}`}
                    >
                       <div className="flex justify-between items-start mb-1">
                          <span className={`font-bold text-sm ${activeEntry?.id === entry.id ? 'text-pepper-900 dark:text-white' : 'text-pepper-600 dark:text-pepper-300'}`}>{entry.title}</span>
                          <span className={`text-[10px] px-1.5 py-0.5 rounded font-bold uppercase ${entry.status === 'Published' ? 'bg-emerald-100 text-emerald-600' : 'bg-pepper-200 text-pepper-600'}`}>
                             {entry.status === 'Published' ? 'Pub' : 'Draft'}
                          </span>
                       </div>
                       <div className="flex justify-between items-center text-[10px] text-pepper-400">
                          <span>{entry.date}</span>
                          <span>{entry.source}</span>
                       </div>
                       <button 
                         onClick={(e) => { e.stopPropagation(); handleDelete(entry.id); }}
                         className="absolute right-2 top-8 p-1.5 text-pepper-300 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 rounded opacity-0 group-hover:opacity-100 transition-all"
                       >
                          <FiTrash2 />
                       </button>
                    </div>
                 ))}
              </div>
           </div>
        </div>

        {/* RIGHT PANE (EDITOR) */}
        <div className="flex-1 flex flex-col bg-pepper-50/50 dark:bg-pepper-950/50 relative">
           
           {generatedContent ? (
             <>
               {/* Editor Toolbar */}
               <div className="h-14 border-b border-pepper-200 dark:border-pepper-800 bg-white dark:bg-pepper-900 flex justify-between items-center px-6 shrink-0">
                  <div className="flex items-center gap-1 bg-pepper-100 dark:bg-pepper-800 p-1 rounded-lg">
                     <button 
                       onClick={() => setViewMode('editor')}
                       className={`px-3 py-1.5 text-xs font-bold rounded-md transition-all flex items-center gap-2 ${viewMode === 'editor' ? 'bg-white dark:bg-pepper-700 text-pepper-900 dark:text-white shadow-sm' : 'text-pepper-500 hover:text-pepper-900 dark:hover:text-pepper-200'}`}
                     >
                       <FiEdit3 /> Editor
                     </button>
                     <button 
                       onClick={() => setViewMode('preview')}
                       className={`px-3 py-1.5 text-xs font-bold rounded-md transition-all flex items-center gap-2 ${viewMode === 'preview' ? 'bg-white dark:bg-pepper-700 text-pepper-900 dark:text-white shadow-sm' : 'text-pepper-500 hover:text-pepper-900 dark:hover:text-pepper-200'}`}
                     >
                       <TbMarkdown /> Preview
                     </button>
                  </div>

                  <div className="flex items-center gap-2">
                     <button onClick={handleCopy} className="p-2 text-pepper-500 hover:text-pepper-900 dark:hover:text-white hover:bg-pepper-100 dark:hover:bg-pepper-800 rounded-lg transition-colors" title="Copy to Clipboard">
                        <FiCopy />
                     </button>
                     <div className="h-4 w-px bg-pepper-200 dark:bg-pepper-700"></div>
                     <button className="flex items-center gap-2 px-3 py-1.5 text-xs font-bold text-pepper-600 dark:text-pepper-300 hover:bg-pepper-100 dark:hover:bg-pepper-800 rounded-lg transition-colors">
                        <FiDownload /> Export
                     </button>
                     <button onClick={handleSave} className="flex items-center gap-2 px-4 py-1.5 bg-pepper-900 dark:bg-white text-white dark:text-pepper-900 rounded-lg text-xs font-bold hover:shadow-md transition-all">
                        <FiCheck /> {activeEntry?.status === 'Published' ? 'Saved' : 'Publish'}
                     </button>
                  </div>
               </div>

               {/* Editor/Preview Area */}
               <div className="flex-1 overflow-hidden relative">
                  {viewMode === 'editor' ? (
                    <textarea 
                      value={generatedContent}
                      onChange={(e) => setGeneratedContent(e.target.value)}
                      className="w-full h-full p-8 bg-transparent text-pepper-800 dark:text-pepper-200 font-mono text-sm leading-relaxed outline-none resize-none custom-scrollbar focus:bg-white dark:focus:bg-pepper-900/50 transition-colors"
                      spellCheck={false}
                    />
                  ) : (
                    <div className="w-full h-full p-8 overflow-y-auto custom-scrollbar">
                       <div className="max-w-3xl mx-auto prose dark:prose-invert prose-pepper prose-headings:font-display prose-headings:font-bold prose-h1:text-3xl prose-h2:text-xl prose-h2:mt-8 prose-h2:mb-4 prose-p:text-pepper-600 dark:prose-p:text-pepper-300 prose-li:text-pepper-600 dark:prose-li:text-pepper-300">
                          {/* Simplified Markdown Rendering for Demo */}
                          {generatedContent.split('\n').map((line, i) => {
                             if (line.startsWith('# ')) return <h1 key={i}>{line.replace('# ', '')}</h1>;
                             if (line.startsWith('## ')) return <h2 key={i}>{line.replace('## ', '')}</h2>;
                             if (line.startsWith('- ')) return <li key={i} className="list-disc ml-4">{line.replace('- ', '')}</li>;
                             if (line.startsWith('_')) return <p key={i} className="italic text-sm text-pepper-400">{line.replace(/_/g, '')}</p>;
                             if (line === '---') return <hr key={i} className="border-pepper-200 dark:border-pepper-700 my-6" />;
                             return <p key={i}>{line}</p>;
                          })}
                       </div>
                    </div>
                  )}
               </div>
             </>
           ) : (
             <div className="flex-1 flex flex-col items-center justify-center text-pepper-400 p-8 text-center">
                <div className="w-24 h-24 bg-pepper-100 dark:bg-pepper-800 rounded-full flex items-center justify-center mb-6">
                   <TbSparkles className="text-4xl text-pepper-300 dark:text-pepper-600" />
                </div>
                <h2 className="text-xl font-bold text-pepper-900 dark:text-white mb-2">Ready to Generate</h2>
                <p className="max-w-md text-sm leading-relaxed mb-8">
                   Select a data source from the left panel and click generate to create a professional changelog using Flownyx AI.
                </p>
                <div className="flex gap-4 opacity-50">
                   <div className="h-32 w-24 bg-white dark:bg-pepper-800 rounded-lg border border-pepper-200 dark:border-pepper-700"></div>
                   <div className="h-32 w-24 bg-white dark:bg-pepper-800 rounded-lg border border-pepper-200 dark:border-pepper-700 translate-y-4"></div>
                   <div className="h-32 w-24 bg-white dark:bg-pepper-800 rounded-lg border border-pepper-200 dark:border-pepper-700"></div>
                </div>
             </div>
           )}
        </div>

      </div>
    </div>
  );
};
